version: '3'

services:

  app:
    build:
      context: ./app
    image: ednelsonpupo/node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  nginx:
    restart: always
    build:
      context: ./nginx
    image: ednelsonpupo/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - db
networks:
  node-network:
    driver: bridge